# 📊 PROMETHEUS KONFIGURACE PRO SEO FARM

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerting_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # SEO Farm Worker metriky
  - job_name: 'seo-farm-worker'
    static_configs:
      - targets: ['host.docker.internal:9090']
    scrape_interval: 10s
    metrics_path: /metrics

  # Node Exporter (systémové metriky)
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Backend API health
  - job_name: 'seo-farm-api'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: /health
    scrape_interval: 30s