id: publish_assistant
enabled: true
model: gpt-4o
temperature: 0.3
input_keys:
  - draft_assistant
  - seo_assistant
  - humanizer_assistant
  - factvalidator_assistant
output_key: publish_assistant
system_prompt_key: publish_article
output_format:
  type: object
  required:
    - title
    - slug
    - meta
    - content_html
    - schema_org
    - format
  properties:
    title:
      type: string
    slug:
      type: string
    meta:
      type: object
    content_html:
      type: string
    schema_org:
      type: string
    format:
      type: string
fallback_if_missing: false